[project]
name = "dbt-models"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dbt-core==1.11.2",
    "dbt-duckdb==1.10.0",
    "dbt-postgres==1.10.0",
    "sqlfluff==4.0.0",
]

[tool.uv.workspace]
members = [
    "test",
]
